refile/refile

lib/refile/image_processing.rb
https://github.com/minimagick/minimagick/blob/master/lib/mini_magick/image.rb#L316
If this is an animated gif, say which 'page' you want with an integer. Default 0 will convert only the first page; 'nil'
will convert all pages.
=> Support to animated gif

lib/refile/attachment/active_record.rb, spec/refile/active_record_helper.rb, spec/refile/attachment/active_record_spec.rb
When updating attachments in nested models, it [fails](https://github.com/refile/refile/issues/142)
This is a fix
=> Nested attachments

lib/refile/attachment/active_record.rb, spec/refile/attachment/active_record_spec.rb
=> fix #227 uploads are not appended when sending in cached files

lib/refile.rb, lib/refile/app.rb, lib/refile/backend_macros.rb, spec/refile/app_spec.rb, spec/refile/backend_examples.rb, spec/refile/backend_macros_spec.rb
Handles uploading exceptions and responds with appropriate status
=> Fix #244: Response codes for exceptions

lib/refile/attachment_definition.rb, spec/refile/attachment/active_record_spec.rb
=> Fix bug when validating empty extension

lib/refile.rb
Changes "pricate" to "private"
=> Fix spelling typo

lib/refile/app.rb, spec/refile/app_spec.rb
Here's a quick fix with spec for the issue I opened in #343
Let me know if it's ok.
=> Fix for #343

README.md
=> Link to the (extracted) refile-s3 in the README

lib/refile/attacher.rb, spec/refile/attachment_spec.rb
This fixes #401, attachment metadata was not removed with attachment
=> Remove metadata

lib/refile/backend/file_system.rb
=> Close uploadable after upload

lib/refile/app.rb, spec/refile/app_spec.rb
so that the client can access/display/download the file
see #429
=> return an url to the just uploaded file in json

lib/refile/rails/attachment_helper.rb, spec/refile/attachment_helper_spec.rb
=> Make attachment_cache_field public

README.md
I found myself in a situation that I had to change the default `mount_point`. As I didn't find this in the Readme, I thought I should open this PR to help others who want to do this. 
Thank you so much for your work.
=> updated readme file to document how to change the default mount_point.

History.md
Version 0.6.2 release date is 2015-10-29 according to [rubygems](https://rubygems.org/gems/refile)
=> Fix gem releasedate

README.md, lib/refile.rb, lib/refile/backend/file_system.rb
1) added notes for case when project has `attachment_*` routes
2) added example of overriding default store folder
3) fixed some typos
=> improve Readme and fix some typos

lib/refile.rb, spec/refile_spec.rb
=> Revert "Use different escape method for filename"

lib/refile/attachment_definition.rb, spec/refile/attachment/active_record_spec.rb
=> Add possibility to specify attachment extensions via Proc

lib/refile.rb, lib/refile/app.rb, spec/refile/app_spec.rb
This is a quick and dirty implementation of expirable download links.
The use case is that we have sensitive attachments for which long-lived download links are unacceptable.
I'd love to get some feedback :)
=> Feature: expirable download links

app/assets/javascripts/refile.js
Here is a suggestion to more convenient way of accessing the signed url when uploading a file.
=> Passes the url parameter (added in #440) to the javascript

lib/refile/file.rb, spec/refile/backend_examples.rb
Continued PR #526. Added specs.
=> Prevent from exposing secure information unexpectedly - specs

README.md
This closes https://github.com/refile/refile/issues/553
=> Add limit examples

.travis.yml, Gemfile, README.md, gemfiles/rails_5.0/Gemfile.rest-client.1.8, gemfiles/rails_5.0/Gemfile.rest-client.2.0, gemfiles/rails_5.0/Gemfile.rest-client.2.1, gemfiles/rails_5.1/Gemfile.rest-client.1.8, gemfiles/rails_5.1/Gemfile.rest-client.2.0, gemfiles/rails_5.1/Gemfile.rest-client.2.1, gemfiles/rails_5.2/Gemfile.rest-client.1.8, gemfiles/rails_5.2/Gemfile.rest-client.2.0, gemfiles/rails_5.2/Gemfile.rest-client.2.1, lib/refile/attachment/active_record.rb, spec/refile/features/single_upload_spec.rb, spec/refile/test_app/app/controllers/single_posts_controller.rb, spec/refile/test_app/app/views/single_posts/form.html.erb, spec/refile/test_app/config/routes.rb
It closes https://github.com/refile/refile/issues/348
=> Allow support for single file upload

app/assets/javascripts/refile.js, lib/refile/rails/attachment_helper.rb, spec/refile/attachment_helper_spec.rb
This pr close #462 
Using disable in hidden field
=> Disable hidden field when metadata is empty

lib/refile/version.rb
Change version from 0.6.2 to 0.7.0 because we can't differ issues using master and the released version
=> Bump version
