.travis.yml
With their new infrastructure also came this ability for open source projects, and bundling itself takes more than 1 minute.
=> Cache gem dependencies on Travis

lib/refile/custom_logger.rb, spec/refile/custom_logger_spec.rb
This defers execution. In the case that the log level is set to
something higher than INFO, it will not execute the block.
Also, add a formatting spec for the logger.
=> Use block form of logger.info

lib/refile/backend_macros.rb, spec/refile/backend_macros_spec.rb
Consider this use case for Refile:
App using Refile also supports UGC markdown with images. Markdown preprocessor in app rewrites image srcs to Refile attachment URLs to a "remote url" to leverage processing, CDN and prevent mixed content warning for non-ssl images. 
Image srcs are `Base64` encoded in attachment urls to resolve to a proper route in `Refile::App`; they must be decoded by the backend for remote retrieval.
Example:
```markdown
```
To support this, I've extracted a few methods that allow backends to customize the default behavior of the `verify_id` macro. These changes would allow our example remote url backend to decode the id and supply its own matcher to verify the id.
=> Extract backend methods

spec/refile/spec_helper.rb
When I run `bundle exec rspec`, then both `Refile::App` and Rails test app are run in "development" environment (which causes Rails to fail, because its `secret_key_base` is only set in "test"). I know I could prepend `RACK_ENV=test` to the shell command, but since this is a standard practice in test environments (rspec-rails and minitest-rails generate it by default), I thought it would nice if Refile test suite also had it.
=> Set RACK_ENV to "test" in spec_helper.rb

spec/refile/attachment/active_record_spec.rb
Assignment of the attachment attribute caches the attachment, but doesn't change any actual columns on the model. Sequel, for example, won't save the record if no columns were changed, thus when replacing an attachment on an existing record it won't trigger the `before_save` callback. So, I thought it's good to have this check for ActiveRecord, just in case.
=> Add ActiveRecord test for replacing files

lib/refile.rb
Cleans up the attachment_url method a bit.
=> Initialize values in method signature instead of using the ||= operator.

Gemfile, lib/refile/file.rb, spec/refile/spec_helper.rb, spec/refile/test_app.rb
1. MRI => `sqlite3`, JRuby => `activerecord-jdbcsqlite3-adapter`
2. Redcarpet has C extensions, which JRuby cannot use, and Redcarpet isn't being used in the test suite anyway.
3. In JRuby `IO.copy_stream` doesn't rewind the destination IO, so we rewind it. I reported it to JRuby, even though I don't really see it as a bug.
4. JRuby doesn't support keyword arguments in block arguments, @jnicklas already reported it, but I think it's easy enough for us to work around it.
5. Cookie middlewares use `ActiveSupport::MessageEncryptor`, which requires that a "Java Cryptography Extension" is installed on the system. Since we don't use cookies in tests, we can just remove them.
This PR is not complete, however. The last remaining error I wasn't able to solve. On normal file upload …
=> Make Refile compatible with JRuby

.rubocop.yml, lib/refile.rb, lib/refile/attacher.rb, lib/refile/attachment.rb, lib/refile/attachment_definition.rb, lib/refile/rails/attachment_helper.rb, spec/refile/attachment_spec.rb
This splits Attacher into two classes, Attacher and AttachmentDefinition. AttachmentDefinition contains all the stuff from attacher that we can know in a static context (that is without having an instance of a record with an attachment). This might seem pretty pointless, but it's a first step towards fixing #6, everyone's favourite issue. (See also #135).
The problem we need to solve to implement for #6 is that we currently use Attacher from the `attachment_field` helper, but this won't work in the future, because we won't have an instance of the record we're trying to build. With this PR we only use AttachmentDefinition for which we only need the class, and not an instance of it.
The disadvantage of this PR is that the naming is all screwed up. AttachmentDefinition is a pretty terrible …
=> Split part of Attacher off into AttachmentDefinition

spec/refile/attachment_spec.rb
Changes "nothign" to "nothing"
[#213](https://github.com/refile/refile/issues/213)
=> Fix spelling typo

lib/refile/attacher.rb
When I was trying to upload large image like [this one](https://markrahrens.files.wordpress.com/2014/03/dsc_1295.jpg).
I see this error IOError: closed stream
Somehow RestClient return closed file when uploaded files are large ( ~ from 15 MB)
And S3 wants this file to be opened
=> Fix uploading large files to S3 via remote_url method

lib/refile/rails/attachment_helper.rb, spec/refile/attachment_helper_spec.rb, spec/refile/spec_helper.rb, spec/refile/test_app.rb
https://github.com/refile/refile/commit/acb99c2f42efa596b9f2d9a3a5f124b5c2df049a
introduced a bug where attachment_tag would previously pass down nil to
attachment_url, but now this is no longer overwritten as Refile.host
also included a failing test :)
@jnicklas
=> fix attachment_tag no longer having cdn host

lib/refile/version.rb
I don't know if it makes sense to merge this at this point, but opened a PR anyway to remind that the version constant is lagging behind the released version.
=> Fix Refile::VERSION to match the release (0.5.4)

app/assets/javascripts/refile.js, lib/refile/rails/attachment_helper.rb, spec/refile/features/direct_upload_spec.rb, spec/refile/test_app/app/controllers/direct_posts_controller.rb, spec/refile/test_app/app/models/post.rb, spec/refile/test_app/app/views/direct_posts/new.html.erb
This isn't a particularly elegant solution, but I couldn't come up with any other way of ensuring that the fields can refer to each other.
=> Find metadata field even when file field is wrapped in error div

README.md
`refile-mini_magick` already has `mini_magick` as a dependency.
=> Remove mini_magick Gemfile line in quick start

README.md
List the [refile-mongoid](https://github.com/krettan/refile-mongoid) extension which implements the `Refile::Mongoid::Attachment` under "Other ORMs".
_Background:_ To use refile in a rails application with mongoid and no ActiveRecord, a gem like [refile-sequel](https://github.com/refile/refile-sequel) is needed. Looked like there was none, so I took the liberty of writing one. It's basically a clone of [refile-sequel](https://github.com/refile/refile-sequel) but using mongo instead.
=> List refile-mongoid as an ORM gem

lib/refile/attachment_definition.rb, spec/refile/attachment/active_record_spec.rb
I found a bug when uploaded file extension name is randomcased. (Iphone creates movies with MOV format for example). And app hasn't content type validation, only extensions list.
I wrote some tests and fixed invalid behaviour.
=> Fix attachment extension validation when extension is in randomcase

.rubocop.yml, refile.gemspec
@jnicklas 
shipping a bunch of test / misc files means download takes longer and vendor/cache gets bigger
adding spec to require-path means the spec files are actually in the gems load path ... but they are not supposed to be required ... right ?
also removing LOAD_PATH modifications
=> ship less files and simplify gemspec

README.md
It isn't needed to add the `aws-sdk` gem since it is a dependency of the `refile-s3` gem.
`https://github.com/refile/refile-s3/blob/master/refile-s3.gemspec#L21`
=> Remove unnecessary instruction

README.md
GraphicsMagick can now be used instead of ImageMagick (See #280).
=> Add a tiny note about GraphicsMagick compatibility

app/assets/javascripts/refile.js
`upload:complete` is being dispatched before `upload:success` or `upload:failure`. I believe this is a bug. I want to track failed uploads and the order of events makes that tricky. I've redacted much of the code for brevity, but it should provide an idea.
```coffeescript
class App.NewUpload
errors: []
template: (index, filename) ->
"""
<tr data-upload="#{index}">
<td>#{filename}</td>
</tr>
"""
constructor: (@form) ->
@setEvents()
setEvents: ->
$(document).on 'upload:failure', @form, (event) =>
@handleFailure event.originalEvent.detail
$(document).on 'upload:complete', @form, @handleComplete
handleFailure: (detail) =>
upload = @findUpload detail.index
@errors.push upload
handleComplete: =>
unless @form.find('input.uploading').length
if @errors.length
@toggleNotice 'Warning'
else …
```
=> ensures that upload:complete is dispatched after upload:success or upload:failure

lib/refile/attacher.rb, spec/refile/attachment_spec.rb
We have some javascript that sends a POST request to Rails containing some metadata about a file pre-uploaded to S3 using the refile-s3 gem. The sent data follows the expected JSON format for Refile, but a gem we're using (JSONAPI::Resources) automatically parses that JSON.
The existing Refile code would assume that the data would be a Refile::File. This PR changes that behavior so that it can be smart about pre-parsed JSON.
=> Added support for receiving parsed json instead of just raw json strings

README.md, lib/refile/rails/attachment_helper.rb
Say one wants to use HTML5's srcset for [responsive image](http://demosthenes.info/blog/944/Responsive-Images-For-Retina-Using-HTML5s-srcset) display. To do that, multiple urls needs to be generated for different devices. `attachment_url` is perfect for this job except that it doesn't have any fallback option as is available in `attachment_image_tag`. This PR adds that option.
The fallback functionality could have been delegated from `attachment_image_tag` to `attachment_url` like this:
```ruby
def attachment_image_tag(record, name, *args, fallback: nil, format: nil, host: Refile.host, **options)
classes = ["attachment", (record.class.model_name.singular if record), name, *options[:class]]
image_tag(attachment_url(record, name, *args, fallback: fallback, format: format, host: host), …
```
=> add fallback option to attachment_url

app/assets/javascripts/refile.js
When using the multiple files feature on Safari (8.0.7 / OS X 10.10.4), sometimes the response to the presign url is cached resulting in the same upload id for multiple files, which in turn results in multiple files overwriting the same cached file.
This change fixes the issue by adding a querystring parameter to the presign url consisting of a timestamp and the file index, therefore avoiding duplicate urls.
=> Prevent AJAX caching errors

README.md
As described in the most recent update to http://www.paulirish.com/2010/the-protocol-relative-url/, it is recommended to always use HTTPS.
=> Recommend using https for the cdn_host

README.md
I've released a refile backend for Gridfs. Is it possible to add a reference to it in the readme ? Thanks.
=> Add a reference to gridfs backend in the readme.

lib/refile/file_double.rb, spec/refile/spec_helper.rb
When I write specs for my own models using Refile, I want an easy way to provide files. The easiest way is to use the Refile::FileDouble class, but currently it's hidden inside the spec helper.
This PR puts FileDouble in the lib directory so it is available to gem users.
If you like the idea I can add a small section to the README about testing your own classes.
=> Make Refile::FileDouble available to gem users

README.md, lib/refile/attachment.rb, lib/refile/attachment/active_record.rb, spec/refile/attachment/active_record_spec.rb
@jnicklas As discussed in #333 this adds a `destroy: true | false` option. It defaults to true. I'm unsure if the documentation is in the right place. Any feedback is welcome!
=> Adds `destroy: true | false` option to `attachment` method

lib/refile/attacher.rb, spec/refile/attachment/active_record_spec.rb, spec/refile/attachment_spec.rb
As discussed in #355, to validates the presence of an attachment, you should be able to do
```ruby
class Attachment < ActiveRecord::Base
attachment :file
validates_presence_of :file
end
```
Setting `attachment.file = nil` raises the exception `undefined method 'size' for nil:NilClass`. This PR fixes this by making `attachment.file = nil` mean the same thing as `attachment.remove_file = true`.
Setting `attachment.file = nil` or `attachment.remove_file = true` will still return the old file in `attachment.file` so the validation passes even though the file will be removed after save. This PR returns `nil` for `attachment.file` if `attacher.remove? == true`.
=> Better support for validating presence of attachment

README.md
I added an example of how to test a model using Refile attachments using the `Refile::FileDouble` helper instead of real files.
=> Add testing example with FileDouble to README

lib/refile/rails/attachment_helper.rb, spec/refile/attachment_helper_spec.rb
Currently, if we call `attachment_field(:image, index: 1)`, Refile omits the `:index` option when rendering the hidden field. This means the hidden field and file field are rendered with different names, e.g.:
```
<input type=hidden name=object[image] ...>
<input type=file   name=object[1][image] ...>
```
This is a bug.
The hidden field and file field need to render with identical `name` attributes in order for file upload to work properly. The name is generated by Rails based on certain options, so we need to make sure that both the field and file receive the same options, at least those options that affect the name. `:index` is one of those options. 
This PR fixes this discrepancy by passing the `:index` option to the hidden field so that the output is correct:
```
<input type=hidden …
```
=> Pass :index option through to hidden field

.gitignore, .rubocop.yml, .travis.yml, Rakefile, gemfiles/Gemfile.rails-5.0-master, refile.gemspec, spec/refile/active_record_helper.rb, spec/refile/app_spec.rb, spec/refile/attachment_helper_spec.rb
This updates refile to test with Rails master branch (rails 5) and fixes all failing tests.  There is still an error when running the tests on travis since for some reason it attempts to load a 'test' file after running rubocop -   I don't have time right now to figure out why, if anyone has any ideas please let me know.  Note currently this requires using a non-official branch of sinatra, hopefully that changes soon
=> rails5 updates

README.md
I suppose it should be : "ActiveRecord integration ships with a nice macro that makes this trivial."
=> forgot word

lib/refile/rails/attachment_helper.rb, spec/refile/attachment_helper_spec.rb
Rails 5 adds a hidden input field for file fields: [commit here](https://github.com/rails/rails/commit/00b26532f05283d2b160308522d1bd2146d6ac18). This breaks refile's keeping the uploaded file across form redisplay (like other fields validations). This PR fixes that by passing the `include_hidden` to the file_filed call.
=> Prevent rails (5) to add an extra hidden input

README.md
We had a situation where we needed to change our `secret_key_base` due to a security policy and because we had some hard coded images (refile attachments) on our blog post everything broke.
After digging a while we realized that refile is using rails `secret_key_base` to generate to token, so it would be nice to have that written in the readme
=> Add notice to Refile.secret_key

lib/refile.rb, spec/refile_spec.rb
This change will make it so escape doesn't replace " " to "+" and downloaded files will have more readable names. (ie `test+example.txt` vs `text example.txt`)
=> Use different escape method for filename

README.md
Added some documentation if you use a catch-all route (for a CMS like [Comfortable Mexican Sofa](https://github.com/comfy/comfortable-mexican-sofa) ) which breaks Refile attachment routing
=> Readme for manual mounting apps with catch-all routes

lib/refile/attachment.rb, spec/refile/attachment_spec.rb
Sometimes it is important to have de presigned URL from Amazon S3. 
It is much faster read direct from there.
=> Return presigned URL from S3

README.md
The current quickstart guide neglects to include necessary fields. If the quickstart were followed precisely, it results in an error.
=> updates quickstart to include all necessary migration fields

lib/refile/attachment_definition.rb, spec/refile/attachment/active_record_spec.rb, spec/refile/attachment_spec.rb
I am using Refile and [Minimagick](https://github.com/minimagick/minimagick) to resize my images on the fly, and sometime our system admin will accidentally upload zero byte file to our server. Then minimagick will raise error when it wants to resize the zero byte file.
Because of this, this PR adds a new option to validate the file size is zero byte or not. Set `allow_zero_byte` to `false` will raise error when users try upload zero byte file to the server.
@sobrinho please let me know this new feature is good to go, so that i will update the README. Thanks!!!
=> Disallow zero byte file upload

lib/refile/attachment/active_record.rb, spec/refile/attachment/active_record_spec.rb
I do not know if this correction is still wanted.
Fixes an error that occurs when trying to assign a file to an attribute that does not track changes or which class inherits from ActiveRecord::Base but does not implement ActiveModel::Dirty.
https://github.com/refile/refile/issues/370
=> Allow assign file to non trackable attribute

config/locales/en.yml, lib/refile/attachment/active_record.rb, lib/refile/attachment_definition.rb, spec/refile/attachment/active_record_spec.rb, spec/refile/attachment_spec.rb, spec/refile/features/direct_upload_spec.rb, spec/refile/features/normal_upload_spec.rb
This PR implements the custom validation message, which return the invalid extension or type that the user is trying to upload and shows the allowed ones.
=> Custom msg format validation

lib/refile/attacher.rb, lib/refile/attachment_definition.rb, spec/refile/attachment/active_record_spec.rb
This PR fixes the `Attacher#content_type` method, in a way that if an **encoding** is appended to content-type response header, now it will be ignored and for now on valid images will pass the validation.
#431
=> Fix 'validate' method to ignore the encoding part in content type

lib/refile/attacher.rb, spec/refile/attachment/active_record_spec.rb
Closes: https://github.com/refile/refile/issues/579
Currently it's not possible to assign a attachment that was previously
set to `nil` without reinitializing the object.
Previously the following code would not work:
```ruby
post.document = nil
post.save
post.document = Refile::DoubleFile.new("hello")
post.save
post.document # => still nil
```
This bug was caused by the `remove` attribute which was set to `true`
when `nil` was assigned but never reset to `false` when a valid
attachment was assigned afterwards.
The previous workaround was to re-create the object eq. calling
something like `post = Post.find(post.id)`
=> Allow assignment of attachment that was previously nil

README.md
I found a typo in this README.
- invalid: `profile_image_content_size`
- valid: `profile_image_size`
=> Fix typo of migration command

.travis.yml, gemfiles/rails_5.0/Gemfile.rest-client.1.8, gemfiles/rails_5.0/Gemfile.rest-client.2.0, gemfiles/rails_5.0/Gemfile.rest-client.2.1, gemfiles/rails_5.1/Gemfile.rest-client.1.8, gemfiles/rails_5.1/Gemfile.rest-client.2.0, gemfiles/rails_5.1/Gemfile.rest-client.2.1, gemfiles/rails_5.2/Gemfile.rest-client.1.8, gemfiles/rails_5.2/Gemfile.rest-client.2.0, gemfiles/rails_5.2/Gemfile.rest-client.2.1, spec/refile/active_record_helper.rb, spec/refile/test_app/app/controllers/presigned_posts_controller.rb
This PR enables CI runners for the following rails versions:
- 5.0
- 5.1
- 5.2
... and removes the jruby-9.1 from it...
=> Add gemfiles for another rails versions

README.md, lib/refile.rb, lib/refile/attachment.rb, lib/refile/attachment/active_record.rb, lib/refile/attachment/multiple_attachments.rb, spec/refile/app_spec.rb, spec/refile/attachment/active_record_spec.rb, spec/refile/attachment_spec.rb, spec/refile/support/accepts_attachments_for_shared_examples.rb
This pull request implements a new `accepts_attachments_for` macro that works with pure Ruby classes. Previously, this macro only worked with Active Record classes. I also kept the Active Record macro.
To accomplish that:
- Macro code has been extracted to a new method called `Refile::Attachment::MultipleUploads#new`. This method generates a module that can be used by both versions of `accepts_attachments_for`.
- To use a PORO, users of the gem will need to implement an interface that's similar to Active Record's. See the README.md file for more details.
- I've moved macro specs to an RSpec shared example and also improved the test coverage.
Also, I had to change the valid `expires_at` from 1 minute to 1 second in the `app_spec.rb` file, in order to avoid CI build failing.
#446
=> Support multiple file upload in POROs

lib/refile/attachment/active_record.rb
This is a very simple fix, but it can cause confusion while reading the source code or using docs.
=> chore: simple fix in the documentation for active record's accepts_attachments_for

README.md
Leaving out `autosave` will only save the attachments when the parent record is created
http://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html
=> Document the 'autosave' option for multiple attachments

lib/refile/app.rb
This patch adds support for a new `quality` parameter that will be forwarded to the image processor.
This patch requires https://github.com/refile/refile-mini_magick/pull/23
**Specs**
Specs are missing since I couldn't find any information on how to run them and I was also not sure how the specs are build up. I can see that there are some dummy processors used that work with strings rather than images. I would love to get some help and add specs for the new parameter.
**Version Requirements**
Since this change requires a specific version of the `refile-mini_magick` gem we would need to somehow ensure that the correct version is present.
Since the gem dependency points from `refile-mini_magick` to `refile` I'm not sure how we would enforce this.
Other processors would also now need to …
=> Support new Quality Option for Processor

lib/refile/app.rb
Reverts refile/refile#594
The spec is failing:
```
$ BUNDLE_GEMFILE=gemfiles/Gemfile_Rails_5_2 bundle exec rspec spec/refile/app_spec.rb:253
WARNING: If you plan to load any of ActiveSupport's core extensions to Hash, be
sure to do so *before* loading Sinatra::Application or Sinatra::Base. If not,
you may disregard this warning.
Set SINATRA_ACTIVESUPPORT_WARNING=false in the environment to hide this warning.
Run options: include {:locations=>{"./spec/refile/app_spec.rb"=>[253]}}
F
Failures:
1) Refile::App GET /:backend/:processor/:id/:filename applies processor with arguments
Failure/Error: expect(last_response.status).to eq(200)
expected: 200
got: 500
(compared using ==)
Finished in 0.04626 seconds (files took 0.81823 seconds to load)
1 example, 1 failure
Failed examples:
rspec …
```
=> Revert "Support new Quality Option for Processor"
